env:
  browser: true
  es6: true
  node: true
extends: 'eslint:recommended'
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
  require: readonly
  cy: readonly
  Cypress: readonly
  describe: readonly
  it: readonly
  expect: readonly
  process: readonly
  __dirname: readonly
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
plugins:
  - react
rules:
  {
    'react/jsx-uses-react': 'error',
    'react/jsx-uses-vars': 'error',
    'no-async-promise-executor': 'off',
  }
